version: 0.2

phases:
  install:
    commands:
      - echo Installing required packages...
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo Running tests...
      - pytest
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  discard-paths: yes
